FlowerProjectP323/Controllers/AboutController.cs
using FlowerProjectP323.DAL;
using FlowerProjectP323.ViewModel.About;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FlowerProjectP323.Controllers
{
    [Authorize]
    public class AboutController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public AboutController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public  async Task <IActionResult> Index()
        {
           
            return View();
        }
    }
}

FlowerProjectP323/ViewComponents/FlowerExpertViewComponent.cs
using FlowerProjectP323.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FlowerProjectP323.ViewComponents
{
	public class FlowerExpertViewComponent :ViewComponent
	{
		private readonly AppDbContext _appDbContext;

		public FlowerExpertViewComponent(AppDbContext appDbContext)
		{
		_appDbContext = appDbContext;
		}
		public async  Task <IViewComponentResult> InvokeAsync()
		{
			var flowerExperts = await _appDbContext.FlowerExperts.ToListAsync();
			return View(flowerExperts);
		}
	}
}

FlowerProjectP323/Views/About/Index.cshtml
@using FlowerProjectP323.ViewModel.About
@model AboutIndexViewModel

<a id='mkdf-back-to-top' href='#'>
	<span class="mkdf-icon-stack">
		<i class="mkdf-icon-font-awesome fa fa-angle-up "></i> <i class="mkdf-icon-font-awesome fa fa-angle-up "></i>
	</span>
</a>
<div class="mkdf-content">
	<div class="mkdf-content-inner">
		<div class="mkdf-title-holder mkdf-centered-type mkdf-title-va-header-bottom mkdf-title-content-va-middle mkdf-preload-background mkdf-has-bg-image mkdf-bg-parallax"
			 style="height: 320px;background-color: #fafaf9;background-image:url(assets/vendor/wp-content/uploads/2018/05/p1-title-img.jpg);"
			 data-height="320">
			<div class="mkdf-title-image">
				<img itemprop="image" src="~/assets/vendor/wp-content/uploads/2018/05/p1-title-img.jpg"
					 alt="a" />
			</div>
			<div class="mkdf-title-wrapper" style="height: 320px">
				<div class="mkdf-title-inner">
					<div class="mkdf-grid">
						<h1 class="mkdf-page-title entry-title">About Us</h1>
						<span class="mkdf-page-subtitle">Where flowers are our inspiration</span>
					</div>
				</div>
			</div>
		</div>
		<div class="mkdf-full-width">
			<div class="mkdf-full-width-inner">
				<div class="mkdf-grid-row">
					<div class="mkdf-page-content-holder mkdf-grid-col-12">
						<section class="wpb-content-wrapper">
							<div class="mkdf-row-grid-section-wrapper ">
								<div class="mkdf-row-grid-section">
									<div class="vc_row wpb_row vc_row-fluid vc_custom_1526291177080">
										<div class="wpb_column vc_column_container vc_col-sm-12">
											<div class="vc_column-inner">
												<div class="wpb_wrapper">
													<div class="mkdf-elements-holder   mkdf-two-columns  mkdf-responsive-mode-1024 ">
														<div class="mkdf-eh-item  mkdf-vertical-alignment-top    "
															 data-item-class="mkdf-eh-custom-4643"
															 data-1024-1366="0px 10% 0px 0px"
															 data-768-1024="0px 29% 80px 0px"
															 data-680-768="0px 17% 80px 0px"
															 data-680="0px 0% 80px 0px">
															<div class="mkdf-eh-item-background-image">
															</div>
															<div class="mkdf-eh-item-inner">
																<div class="mkdf-eh-item-content mkdf-eh-custom-4643"
																	 style="padding: 28px 10% 0px 0px">
																	<div class="mkdf-section-title-holder  mkdf-st-disable-title-break mkdf-st-subtitle-pos-under">
																		<div class="mkdf-st-inner">
																			<h2 class="mkdf-st-title">
																				We take <span class="mkdf-st-title-highlight">flowers</span>
																				personally<br /> &amp; we
																				bring you happiness
																			</h2>
																			<p class="mkdf-st-text"
																			   style="font-size: 17px;line-height: 29px;margin-top: 27px">
																				Lorem ipsum dolor sit amet,
																				consectetuer adipiscing
																				elit. Aenean commodo ligula
																				eget dolor. Aenean massa.
																				Cum sociis natoque penatibus
																				et magnis dis parturient
																				montes, nascetur ridiculus
																				mus. Donec quam felis,
																				ultricies nec.
																			</p>
																		</div>
																	</div>
																	<div class="vc_empty_space"
																		 style="height: 42px">
																		<span class="vc_empty_space_inner"></span>
																	</div>
																	<div class="mkdf-single-image-holder   ">
																		<div class="mkdf-si-inner">
																			<img width="197" height="56"
																				 src="~/assets/vendor/wp-content/uploads/2018/04/h2-sign-img.png"
																				 class="attachment-full size-full"
																				 alt="s"
																				 srcset="https://fiorello.qodeinteractive.com/wp-content/uploads/2018/04/h2-sign-img.png 197w, https://fiorello.qodeinteractive.com/wp-content/uploads/2018/04/h2-sign-img-75x21.png 75w"
																				 sizes="(max-width: 197px) 100vw, 197px"
																				 loading="eager" />
																		</div>
																	</div>
																</div>
															</div>
														</div>
														<div class="mkdf-eh-item      "
															 data-item-class="mkdf-eh-custom-9986">
															<div class="mkdf-eh-item-background-image">
															</div>
															<div class="mkdf-eh-item-inner">
																<div class="mkdf-eh-item-content mkdf-eh-custom-9986"
																	 style="padding: 0 0 0 0 ">
																	<div class="mkdf-video-button-holder  mkdf-vb-has-img">
																		<div class="mkdf-video-button-image">
																			<img width="800" height="518"
																				 src="~/assets/vendor/wp-content/uploads/2018/04/h3-video-img.jpg"
																				 class="attachment-full size-full"
																				 alt="a"
																				 srcset="https://fiorello.qodeinteractive.com/wp-content/uploads/2018/04/h3-video-img.jpg 800w, https://fiorello.qodeinteractive.com/wp-content/uploads/2018/04/h3-video-img-300x194.jpg 300w, https://fiorello.qodeinteractive.com/wp-content/uploads/2018/04/h3-video-img-768x497.jpg 768w, https://fiorello.qodeinteractive.com/wp-content/uploads/2018/04/h3-video-img-225x146.jpg 225w, https://fiorello.qodeinteractive.com/wp-content/uploads/2018/04/h3-video-img-75x50.jpg 75w"
																				 sizes="(max-width: 800px) 100vw, 800px"
																				 loading="eager" />
																		</div>
																		<a class="mkdf-video-button-play"
																		   href="https://www.youtube.com/watch?v=K-0cjGCNYfs"
																		   target="_self"
																		   data-rel="prettyPhoto[video_button_pretty_photo_419]">
																			<span class="mkdf-video-button-play-inner">
																				<span class="mkdf-video-button-outer">
																					<span class="arrow_triangle-right"></span>
																				</span>
																			</span>
																		</a>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="vc_row wpb_row vc_row-fluid vc_custom_1526291277718"
								 style="background-color:#f8f8f8">
								<div class="wpb_column vc_column_container vc_col-sm-12">
									<div class="vc_column-inner">
										<div class="wpb_wrapper">
											<div class="mkdf-row-grid-section-wrapper mkdf-content-aligment-center">
												<div class="mkdf-row-grid-section">
													<div class="vc_row wpb_row vc_inner vc_row-fluid vc_custom_1525433824560">
														<div class="wpb_column vc_column_container vc_col-sm-12 vc_col-lg-offset-3 vc_col-lg-6 vc_col-md-offset-1 vc_col-md-10">
															<div class="vc_column-inner">
																<div class="wpb_wrapper">
																	<div class="mkdf-section-title-holder   mkdf-st-subtitle-pos-under">
																		<div class="mkdf-st-inner">
																			<h2 class="mkdf-st-title">
																				Flower Experts
																			</h2>
																			<p class="mkdf-st-text"
																			   style="font-size: 17px;line-height: 29px">
																				A perfect blend of
																				creativity, energy,
																				communication, happiness and
																				love. Let us arrange a smile
																				for you.
																			</p>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
											@await Component.InvokeAsync("FlowerExpert")
										</div>
									</div>
								</div>
							</div>
							<div class="mkdf-row-grid-section-wrapper ">
								<div class="mkdf-row-grid-section">
									<div class="vc_row wpb_row vc_row-fluid vc_custom_1526292063574">
										<div class="wpb_column vc_column_container vc_col-sm-12 vc_col-lg-offset-2 vc_col-lg-8">
											<div class="vc_column-inner">
												<div class="wpb_wrapper">
													<div class="mkdf-testimonials-holder mkdf-testimonials-standard  clearfix">
														<div class="mkdf-testimonials mkdf-owl-slider"
															 data-number-of-items="1"
															 data-enable-autoplay="yes"
															 data-slider-speed="5000"
															 data-slider-speed-animation="600"
															 data-enable-navigation="yes"
															 data-enable-pagination="no">
															<div class="mkdf-testimonial-content"
																 id="mkdf-testimonials-62">
																<div class="mkdf-testimonial-image">
																	<img width="87" height="87"
																		 src="~/assets/vendor/wp-content/uploads/2018/04/testimonial-img-2.png"
																		 class="attachment-87x87 size-87x87 wp-post-image"
																		 alt="a"
																		 srcset="https://fiorello.qodeinteractive.com/wp-content/uploads/2018/04/testimonial-img-2.png 87w, https://fiorello.qodeinteractive.com/wp-content/uploads/2018/04/testimonial-img-2-50x50.png 50w"
																		 sizes="(max-width: 87px) 100vw, 87px"
																		 loading="eager" />
																</div>
																<div class="mkdf-testimonial-text-holder">
																	<p class="mkdf-testimonial-text">
																		Nullam
																		dictum felis eu pede mollis pretium.
																		Integer tincidunt. Cras dapibus
																		lingua.
																	</p>
																	<span class="mkdf-testimonial-author">
																		<span class="mkdf-testimonials-author-name">
																			Anna
																			Barnes
																		</span>
																		<span class="mkdf-testimonials-author-job">Florist</span>
																	</span>
																</div>
															</div>
															<div class="mkdf-testimonial-content"
																 id="mkdf-testimonials-8">
																<div class="mkdf-testimonial-image">
																	<img width="87" height="87"
																		 src="~/assets/vendor/wp-content/uploads/2018/04/testimonial-img-1.png"
																		 class="attachment-87x87 size-87x87 wp-post-image"
																		 alt="a" loading="eager"
																		 srcset="https://fiorello.qodeinteractive.com/wp-content/uploads/2018/04/testimonial-img-1.png 87w, https://fiorello.qodeinteractive.com/wp-content/uploads/2018/04/testimonial-img-1-50x50.png 50w"
																		 sizes="(max-width: 87px) 100vw, 87px" />
																</div>
																<div class="mkdf-testimonial-text-holder">
																	<p class="mkdf-testimonial-text">
																		Lorem
																		ipsum dolor sit amet, consectetuer
																		adipiscing elit. Aenean commodo
																		ligula eget.
																	</p>
																	<span class="mkdf-testimonial-author">
																		<span class="mkdf-testimonials-author-name">
																			Jasmine
																			White
																		</span>
																		<span class="mkdf-testimonials-author-job">Florist</span>
																	</span>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</section>
					</div>
				</div>
			</div>
		</div>
		<div class="mkdf-content-bottom">
			<div class="mkdf-content-bottom-inner mkdf-full-width">
				<div class="widget widget_mkdf_instagram_widget"></div>
			</div>
		</div>
	</div>
</div>